# Generated by Django 3.0.5 on 2020-04-09 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0002_auto_20200408_1111'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='listrow',
            order_with_respect_to=None,
        ),
    ]
