# Generated by Django 3.0.5 on 2020-04-09 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0003_auto_20200409_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listrow',
            options={'ordering': ['list__name', 'position']},
        ),
    ]
